#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           8

# Border colors
bspc config normal_border_color "#ffffff"
bspc config focused_border_color "#171717"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-center /home/law/Downloads/wallpaper.jpg
nm-applet --no-agent &
xsetroot -cursor_name left_ptr &
xss-lock xsecurelock &
#conky &
~/.config/polybar/launch.sh
~/apps/scripts/bspwmbeg.sh copyq picom dunst
